baseURL = "https://example.com"
languageCode = 'en-gb'
title = "Example Yinante Blog"
theme = "yinante"
DefaultContentLanguage = "en"
paginate = 5
summaryLength = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "Simon Bowie"
  homepage = "https://simonxix.com/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
mainSections = ["posts"]
headTitle = "Example Yinante Blog"
description = 'example'
footer = 'This website is © 2023 ... and is licensed under a ... license.'
count = 
disqus = "joway" # disqus account name
extraHead = ''

[[params.links]]
name = "About"
link = "/about"

[[params.links]]
name = "RSS"
link = "/index.xml"
new_tab = true

[[params.links]]
name = "SimonXIX"
link = "https://simonxix.com"
new_tab = true

postHeaderContent = ""
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []